name: Trigger auto deployment for siemens-mo-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/siemens-mo-container-app-AutoDeployTrigger-38051cdf-f8ba-496b-a82e-78fc882af196.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIEMENSMOCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: siemensmotusharreg.azurecr.io
          registryUsername: ${{ secrets.SIEMENSMOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SIEMENSMOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: siemens-mo-container-app
          resourceGroup: siemens-rg-mo-container-apps
          imageToBuild: siemensmotusharreg.azurecr.io/siemens-mo-container-app:${{ github.sha }}
          
            

     

